### ISSUE TITLE
provide releases

### ISSUE THREAD

**Issue by oeneme** [pia-foss/extension-chrome#8]
Could you provide releases? It would make the installation process much easier.

https://github.com/pia-foss/extension-chrome/releases

**Comment by DanAtkinson** [comment]
According to the [Chrome extension](https://chrome.google.com/webstore/detail/private-internet-access/jplnlifepflhkbkgonidnobkakhmpnmh), the current version is 1.5.0. However, the earliest version number in the source code here is [1.5.3](https://github.com/pia-foss/extension-chrome/commit/8159f75af4c8b88d6008032a4509508e1a6cd910#diff-021321e8c168ba3ae39ce3a2e7b3ec87) as seen in the initial commit.

Given that the currently released version is older than the oldest release here, it makes sense that there are no releases as yet as these would have been before PIA open-sourced their code.

With all that being said however, it's clear that changes are being made, and the current version is 1.5.10. I am still having [trouble](3) compiling the extension, so having a compiled version would be great.

**Comment by oeneme** [comment]
Probably for Chrome this issue goes for other platforms as well.

I've loaded extensions using Chromium on both Linux and Windows and not experienced this issue.

Anyhow I'm looking forward to the next release, you guys keep making it really hard for me not to use PIA ;)

**Comment by DanAtkinson** [comment]
@oeneme Hi. I believe this is now pertinent given that PIA has been updated to 1.5.10 which now matches the current version in the codebase.

![image](https://user-images.githubusercontent.com/23440/39983730-97f62538-5750-11e8-94a5-ec0d4f96b953.png)

Please can you upload the released extension to the codebase?

Thanks, Dan

**Comment by DanAtkinson** [comment]
Please upload the release for 1.5.11, or create a script which automatically tag releases.

Thanks, Dan

**Comment by taesup** [comment]
Provided a release for 1.5.11.
